# Generated by Django 4.2.27 on 2026-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, help_text='Album cover image', null=True, upload_to='covers/'),
        ),
    ]
