# Generated by Django 4.2.27 on 2026-02-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='emotion',
            field=models.CharField(blank=True, choices=[('happy', 'Vui'), ('sad', 'Buồn'), ('relaxed', 'Thư giãn'), ('contemplative', 'Sâu lắng'), ('unknown', 'Chưa phân loại')], default='unknown', help_text='Cảm xúc được phân loại bởi AI', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='emotion_confidence',
            field=models.FloatField(default=0.0, help_text='Độ tin cậy của AI (0.0 - 1.0)'),
        ),
    ]
